from __future__ import annotations

from .artifacts import placeholder_artifacts
from .config import settings
from .schemas import ImageWorkerRequest, ImageWorkerResponse


class PlaceholderImageBackend:
    def generate(self, payload: ImageWorkerRequest) -> ImageWorkerResponse:
        artifacts = placeholder_artifacts.create_image_bundle(
            generation_id=payload.generation_id,
            prompt=payload.prompt,
            request=payload.request,
        )
        return ImageWorkerResponse(
            generation_id=payload.generation_id,
            engine="placeholder",
            message="image artifact generated by private image worker",
            artifacts=artifacts,
        )


class DiffusersImageBackend:
    def generate(self, payload: ImageWorkerRequest) -> ImageWorkerResponse:
        raise NotImplementedError(
            "The diffusers image backend is not wired yet. Connect a GPU machine and implement the model loader here."
        )


class ImageWorkerService:
    def __init__(self) -> None:
        self.placeholder_backend = PlaceholderImageBackend()
        self.diffusers_backend = DiffusersImageBackend()

    def generate(self, payload: ImageWorkerRequest) -> ImageWorkerResponse:
        if settings.image_engine == "placeholder":
            return self.placeholder_backend.generate(payload)
        if settings.image_engine == "diffusers":
            return self.diffusers_backend.generate(payload)
        raise ValueError(f"Unsupported image engine: {settings.image_engine}")


image_worker = ImageWorkerService()
